export const BOARD_WIDTH = 1536;
export const BOARD_HEIGHT = 1024;

export const PLAY_AREA_LEFT = 250;
export const PLAY_AREA_WIDTH = 1000;
export const PLAY_AREA_RIGHT = PLAY_AREA_LEFT + PLAY_AREA_WIDTH;
export const PLAY_AREA_CENTER_X = PLAY_AREA_LEFT + PLAY_AREA_WIDTH / 2;
export const PLAY_AREA_CENTER_OFFSET = PLAY_AREA_CENTER_X - BOARD_WIDTH / 2;

export const UNIT_TOKEN_SIZE_PX = 144;
export const UNIT_TOKEN_RADIUS_PX = UNIT_TOKEN_SIZE_PX / 2;
