export const HERO_HEALTH = 30;
export const MAX_MANA = 10;
export const MAX_HAND_SIZE = 10;
export const MAX_BOARD_SIZE = 7;

export const PLAYER_ID = "player";
export const ENEMY_ID = "enemy";

export const STARTING_HAND_SIZE = 5;

export const DEFAULT_SEED = 1337;

export const PLAYER_DECK = [
  "VOID_VOID_INITIATE",
  "VOID_UMBRAL_THRALL",
  "VOID_VOIDBOUND_ACOLYTE",
  "VOID_ABYSSAL_WATCHER",
  "VOID_GRAVETIDE_COLLECTOR",
  "VOID_HOLLOW_SENTINEL",
  "VOID_VOID_LEECH",
  "VOID_DUSK_HERALD",
  "VOID_OBSIDIAN_WARDEN",
  "VOID_GRASP_OF_NOTHING",
  "VOID_SHADOW_RECLAIM",
  "VOID_GRAVE_OFFERING",
  "VOID_SILENCE_THE_LIGHT",
  "VOID_ENCROACHING_VOID",
];

export const ENEMY_DECK = [
  "EMBER_EMBERFOOT_SOLDIER",
  "EMBER_ASHBOUND_INITIATE",
  "EMBER_CINDERBLADE_RAIDER",
  "EMBER_FLAMEFORGED_BRUTE",
  "EMBER_ASHSPIRE_VANGUARD",
  "EMBER_EMBER_HOUND",
  "EMBER_MOLTEN_CHAMPION",
  "EMBER_PYREBOUND_KNIGHT",
  "EMBER_INFERNAL_COLOSSUS",
  "EMBER_SCORCHING_COMMAND",
  "EMBER_ASHFALL_STRIKE",
  "EMBER_FLAME_SURGE",
  "EMBER_BATTLE_CRY_OF_EMBERS",
  "EMBER_MOLTEN_VERDICT",
  "EMBER_BURN_THE_WEAK",
];
