export type UIAssetType = "img" | "bg";
export type UIAssetFallback = "none" | "gradient";
export type UIAssetFit = "cover" | "contain";

export type UIAsset = {
  key: string;
  path: string;
  type: UIAssetType;
  fallback: UIAssetFallback;
  fit: UIAssetFit;
  aspect?: string;
};

const UI_ASSETS_RAW = {
  backgroundGlobal: {
    key: "backgroundGlobal",
    path: "/assets/ui/global-bg.png",
    type: "bg",
    fallback: "gradient",
    fit: "cover",
  },
  mainMenuProfileAvatar: {
    key: "mainMenuProfileAvatar",
    path: "/assets/ui/portraits/player-avatar.png",
    type: "img",
    fallback: "gradient",
    fit: "cover",
    aspect: "1 / 1",
  },
  mainMenuStoneStructure: {
    key: "mainMenuStoneStructure",
    path: "/assets/ui/mainmenu/mainmenu-stone-structure.png",
    type: "img",
    fallback: "gradient",
    fit: "contain",
    aspect: "free",
  },
  mainMenuHeader: {
    key: "mainMenuHeader",
    path: "/assets/ui/mainmenu/mainmenu-header.png",
    type: "img",
    fallback: "gradient",
    fit: "contain",
    aspect: "free",
  },
  mainMenuHeaderText: {
    key: "mainMenuHeaderText",
    path: "/assets/ui/mainmenu/mainmenu-header-text.png",
    type: "img",
    fallback: "gradient",
    fit: "contain",
    aspect: "free",
  },
  mainMenuPillarSupports: {
    key: "mainMenuPillarSupports",
    path: "/assets/ui/mainmenu/mainmenu-pillar-supports.png",
    type: "img",
    fallback: "gradient",
    fit: "contain",
    aspect: "free",
  },
  mainMenuQuestsBadge: {
    key: "mainMenuQuestsBadge",
    path: "/assets/ui/mainmenu/mainmenu-quest-icon.png",
    type: "img",
    fallback: "gradient",
    fit: "contain",
    aspect: "3 / 2",
  },
  mainMenuPlayerPanel: {
    key: "mainMenuPlayerPanel",
    path: "/assets/ui/mainmenu/mainmenu-player_frame.png",
    type: "img",
    fallback: "gradient",
    fit: "contain",
    aspect: "721 / 823",
  },
  mainMenuNavShelf: {
    key: "mainMenuNavShelf",
    path: "/assets/ui/mainmenu/mainmenu-nav-shelf.png",
    type: "img",
    fallback: "gradient",
    fit: "contain",
    aspect: "free",
  },
  mainMenuButtonActive: {
    key: "mainMenuButtonActive",
    path: "/assets/ui/mainmenu/btn-play_active.png",
    type: "img",
    fallback: "gradient",
    fit: "contain",
    aspect: "free",
  },
  mainMenuButtonInactive: {
    key: "mainMenuButtonInactive",
    path: "/assets/ui/mainmenu/btn-play_inactive.png",
    type: "img",
    fallback: "gradient",
    fit: "contain",
    aspect: "free",
  },
  mainMenuHeroFeature: {
    key: "mainMenuHeroFeature",
    path: "/assets/ui/portraits/main-menu-feature.png",
    type: "bg",
    fallback: "gradient",
    fit: "cover",
  },
  storePackArt: {
    key: "storePackArt",
    path: "/assets/ui/store/store-pack.png",
    type: "img",
    fallback: "gradient",
    fit: "cover",
    aspect: "4 / 5",
  },
  storeFeaturedArt: {
    key: "storeFeaturedArt",
    path: "/assets/ui/store/store-featured.png",
    type: "img",
    fallback: "gradient",
    fit: "cover",
  },
  storeCurrentPackPortrait: {
    key: "storeCurrentPackPortrait",
    path: "/assets/ui/store/store-current-pack.png",
    type: "img",
    fallback: "gradient",
    fit: "cover",
    aspect: "1 / 1",
  },
  storeCurrentPackIcon: {
    key: "storeCurrentPackIcon",
    path: "/assets/ui/icons/pack-icon.png",
    type: "img",
    fallback: "gradient",
    fit: "contain",
    aspect: "1 / 1",
  },
  profileHeaderCrest: {
    key: "profileHeaderCrest",
    path: "/assets/ui/frames/profile-crest.png",
    type: "img",
    fallback: "gradient",
    fit: "contain",
    aspect: "1 / 1",
  },
  playflowHeaderCrest: {
    key: "playflowHeaderCrest",
    path: "/assets/ui/frames/playflow-crest.png",
    type: "img",
    fallback: "gradient",
    fit: "contain",
    aspect: "1 / 1",
  },
  profilePortrait: {
    key: "profilePortrait",
    path: "/assets/ui/portraits/profile-hero.png",
    type: "img",
    fallback: "gradient",
    fit: "cover",
    aspect: "3 / 4",
  },
  profileAchievementIcon: {
    key: "profileAchievementIcon",
    path: "/assets/ui/icons/achievement.png",
    type: "img",
    fallback: "gradient",
    fit: "contain",
    aspect: "1 / 1",
  },
  profileAbilityIcon: {
    key: "profileAbilityIcon",
    path: "/assets/ui/icons/ability.png",
    type: "img",
    fallback: "gradient",
    fit: "contain",
    aspect: "1 / 1",
  },
  heroProfileHeaderCrest: {
    key: "heroProfileHeaderCrest",
    path: "/assets/ui/frames/hero-profile-crest.png",
    type: "img",
    fallback: "gradient",
    fit: "contain",
    aspect: "1 / 1",
  },
  heroProfileNameIcon: {
    key: "heroProfileNameIcon",
    path: "/assets/ui/icons/hero-class.png",
    type: "img",
    fallback: "gradient",
    fit: "contain",
    aspect: "1 / 1",
  },
  heroProfilePortrait: {
    key: "heroProfilePortrait",
    path: "/assets/ui/portraits/hero-profile.png",
    type: "img",
    fallback: "gradient",
    fit: "cover",
    aspect: "4 / 5",
  },
  collectionHeroPortrait: {
    key: "collectionHeroPortrait",
    path: "/assets/ui/portraits/collection-hero.png",
    type: "img",
    fallback: "gradient",
    fit: "cover",
    aspect: "4 / 5",
  },
  collectionDeckIcon: {
    key: "collectionDeckIcon",
    path: "/assets/ui/icons/deck-icon.png",
    type: "img",
    fallback: "gradient",
    fit: "contain",
    aspect: "1 / 1",
  },
  collectionCardArt: {
    key: "collectionCardArt",
    path: "/assets/ui/portraits/collection-card.png",
    type: "img",
    fallback: "gradient",
    fit: "cover",
  },
  questsHeaderIcon: {
    key: "questsHeaderIcon",
    path: "/assets/ui/icons/quest-scroll.png",
    type: "img",
    fallback: "gradient",
    fit: "contain",
    aspect: "1 / 1",
  },
  questCardArt: {
    key: "questCardArt",
    path: "/assets/ui/quests/quest-card.png",
    type: "img",
    fallback: "gradient",
    fit: "cover",
    aspect: "4 / 3",
  },
  iconGold: {
    key: "iconGold",
    path: "/assets/ui/icons/gold.png",
    type: "img",
    fallback: "gradient",
    fit: "contain",
    aspect: "1 / 1",
  },
  iconShard: {
    key: "iconShard",
    path: "/assets/ui/icons/shard.png",
    type: "img",
    fallback: "gradient",
    fit: "contain",
    aspect: "1 / 1",
  },
  questChest: {
    key: "questChest",
    path: "/assets/ui/quests/quest-chest.png",
    type: "img",
    fallback: "gradient",
    fit: "cover",
    aspect: "1 / 1",
  },
  questWeeklyPack: {
    key: "questWeeklyPack",
    path: "/assets/ui/quests/quest-pack.png",
    type: "img",
    fallback: "gradient",
    fit: "cover",
    aspect: "4 / 5",
  },
  worldMapPanel: {
    key: "worldMapPanel",
    path: "/assets/ui/worldmap/world-map.png",
    type: "bg",
    fallback: "gradient",
    fit: "cover",
  },
  heroPortraitAeria: {
    key: "heroPortraitAeria",
    path: "/assets/ui/portraits/hero-aeria.png",
    type: "img",
    fallback: "gradient",
    fit: "cover",
    aspect: "4 / 5",
  },
  heroPortraitKael: {
    key: "heroPortraitKael",
    path: "/assets/ui/portraits/hero-kael.png",
    type: "img",
    fallback: "gradient",
    fit: "cover",
    aspect: "4 / 5",
  },
  heroPortraitSolene: {
    key: "heroPortraitSolene",
    path: "/assets/ui/portraits/hero-solene.png",
    type: "img",
    fallback: "gradient",
    fit: "cover",
    aspect: "4 / 5",
  },
  heroPortraitLyra: {
    key: "heroPortraitLyra",
    path: "/assets/heroes/lyra.png",
    type: "img",
    fallback: "gradient",
    fit: "cover",
    aspect: "4 / 5",
  },
  heroPortraitTharos: {
    key: "heroPortraitTharos",
    path: "/assets/heroes/tharos.png",
    type: "img",
    fallback: "gradient",
    fit: "cover",
    aspect: "4 / 5",
  },
  heroPortraitVarya: {
    key: "heroPortraitVarya",
    path: "/assets/ui/portraits/hero-varya.png",
    type: "img",
    fallback: "gradient",
    fit: "cover",
    aspect: "4 / 5",
  },
  heroPortraitPlaceholder: {
    key: "heroPortraitPlaceholder",
    path: "/assets/ui/portraits/hero-placeholder.png",
    type: "img",
    fallback: "gradient",
    fit: "cover",
    aspect: "4 / 5",
  },
  selectedHeroPortrait: {
    key: "selectedHeroPortrait",
    path: "/assets/ui/matchmaking/selected-hero.png",
    type: "img",
    fallback: "gradient",
    fit: "cover",
    aspect: "4 / 5",
  },
  opponentHeroPortrait: {
    key: "opponentHeroPortrait",
    path: "/assets/ui/matchmaking/opponent-hero.png",
    type: "img",
    fallback: "gradient",
    fit: "cover",
    aspect: "4 / 5",
  },
  astraOrb: {
    key: "astraOrb",
    path: "/assets/ui/astra/astra-orb.png",
    type: "img",
    fallback: "gradient",
    fit: "contain",
    aspect: "1 / 1",
  },
  astraPortrait: {
    key: "astraPortrait",
    path: "/assets/ui/astra/astra-portrait.png",
    type: "img",
    fallback: "gradient",
    fit: "cover",
    aspect: "1 / 1",
  },
  astraCoachmark: {
    key: "astraCoachmark",
    path: "/assets/ui/astra/astra-coachmark.png",
    type: "img",
    fallback: "gradient",
    fit: "cover",
    aspect: "1 / 1",
  },
  astraContextFrame: {
    key: "astraContextFrame",
    path: "/assets/ui/astra/astra-context-frame.png",
    type: "img",
    fallback: "gradient",
    fit: "contain",
  },
} as const satisfies Record<string, UIAsset>;

export type UIAssetKey = keyof typeof UI_ASSETS_RAW;

export const UI_ASSETS: Record<UIAssetKey, UIAsset> = UI_ASSETS_RAW as Record<UIAssetKey, UIAsset>;

export const HERO_PORTRAIT_KEYS: Record<string, UIAssetKey> = {
  AERIA: "heroPortraitAeria",
  KAEL: "heroPortraitKael",
  SOLENE: "heroPortraitSolene",
  LYRA: "heroPortraitLyra",
  THAROS: "heroPortraitTharos",
  VARYA: "heroPortraitVarya",
};
